### ISSUE TITLE
I need suport in Express 4.X.X

### ISSUE THREAD

**Issue by Pompeu** [brikteknologier/seraph-resource#38]
i try use this resource and get a problen with , Controller Module
how i can proceed with this?

**Comment by oren** [comment]
yes. express 4 doesn't have `.json()`

I tried fixing it by requiring body-parser:

```
8  var bodyParser = require('body-parser'); 
9  var parserJson = naan.curry(bodyParser.json, { strict: false });
10 var parserUrlEncoded = naan.curry(bodyParser.urlencoded, { strict: false });
```

and I get:
TypeError: app.use() requires middleware functions
    at EventEmitter.use (/home/oren/projects/neo/node_modules/express/lib/application.js:209:11)

**Comment by jonpacker** [comment]
`seraph-resource` unfortunately does not support express 4, as the `controller` model needs a near total rewrite to work with it. Unfortunately I don't have time or plans in the near feature to do this, sorry.

**Comment by oren** [comment]
@jonpacker thank for the reply. I am curious, are you using seraph-resource for your projects or was it just an experiment and you decided that you don't need it. the same question for the 'seraph' and 'seraph-model' repositories.

Thanks

**Comment by jonpacker** [comment]
We use seraph, seraph-resource and seraph-mode in production with express 3.

**Comment by stigrv** [comment]
Already available here:
https://github.com/mostlyserious/seraph-resource
